version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  mongodb:
     container_name: mongodb
     ports:
      - 27017:27017
     volumes:
      - ~/apps/mongo:/data/mongo
     environment:
      - MONGO_INITDB_ROOT_USERNAME=guest
      - MONGO_INITDB_ROOT_PASSWORD=guest
      - MONGO_INITDB_DATABASE=contactmanager

  mongo-express:
     container_name: mongo.express
     restart: always
     ports:
      - 8081:8081
     environment:
       ME_CONFIG_MONGODB_SERVER: mongodb
       ME_CONFIG_MONGODB_ADMINUSERNAME: guest
       ME_CONFIG_MONGODB_ADMINPASSWORD: guest
     depends_on:
      - mongodb

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-guest}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-guest}
      PGDATA: /data/postgres
    volumes:
       - ~/apps/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  gateway:
    container_name: gateway
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - report.api
      - contact.manager.api

  contact.manager.api:
    container_name: contact.manager.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8002:80"
      - "8003:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - rabbitmq
      - mongo-express
  
  report.api:
    container_name: report.api
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8004:80"
      - "8005:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - rabbitmq
      - mongo-express
